name: "[PROD] deploy"

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      project_name: "cidade-refugio-backend"
      # aws-assume-role-arn: "" 
      aws-region: "sa-east-1"
    secrets: inherit 