name: "[DEV] deploy"

on: 
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  terraform-deploy:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      id_aws_account_dev: "164599051832"
      project_name: "cidade-refugio-backend"
      aws-statefile-s3-bucket: "cidade-refugio-backend-terraform-state-164599051832"
      aws-region: "sa-east-1"
    secrets: inherit