name: "Terraform Execution"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      project_name:
        type: string
        required: true
      aws-assume-role-arn:
        type: string
        required: false 
      aws-region:
        type: string
        required: true
      id_aws_account_dev:
        type: string
        required: false
      id_aws_account_prod:
        type: string
        required: false
      destroy:
        type: boolean
        required: false
        default: false

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: ${{ inputs.aws-region }} 
      TF_VAR_project_name: ${{ inputs.project_name }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_id_aws_account_dev: ${{ inputs.id_aws_account_dev }}
      TF_VAR_id_aws_account_prod: ${{ inputs.id_aws_account_prod }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Se o ARN for enviado, ele usa OIDC. 
          # Se não for, ele tentará usar as chaves das Secrets automaticamente.
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: |
          if [ "${{ inputs.environment }}" == "prod" ]; then
            ACCOUNT_ID="${{ inputs.id_aws_account_prod }}" 
          else
            ACCOUNT_ID="${{ inputs.id_aws_account_dev }}"
          fi

          cd infra && \
            -backend-config="cidade-refugio-backend-terraform-state-${ACCOUNT_ID}" \
            -backend-config="key=${{ inputs.project_name }}/terraform.tfstate" \
            -backend-config="region=${{ inputs.aws-region }}" \
            -backend-config="dynamodb_table=cidade-refugio-backend-terraform-state-lock" \
            -backend-config="encrypt=true"

      - name: Terraform Apply/Destroy
        run: |
          cd infra && \
          terraform workspace select -or-create ${{ inputs.environment }} && \
          if [ "${{ inputs.destroy }}" = "true" ]; then
            terraform destroy -auto-approve \
              -var="environment=${{ inputs.environment }}" \
              -var="aws_region=${{ inputs.aws-region }}"
          else
            terraform apply -auto-approve \
              -var="environment=${{ inputs.environment }}" \
              -var="aws_region=${{ inputs.aws-region }}"
          fi