name: "IAM Bootstrap (Initial Setup)"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite rodar manualmente se precisar

jobs:
  bootstrap:
    name: "Create Central Role"
    runs-on: ubuntu-latest
    
    # IMPORTANTE: Aqui usamos o método legado (Secrets) 
    # porque a Role ainda não existe para usarmos OIDC.
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: |
          cd infra-base && \
          terraform init

      - name: Terraform Apply
        run: |
          cd infra-base && \
          terraform apply -auto-approve
